# Generated by Django 3.1.1 on 2020-09-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200909_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default=2, upload_to='book/'),
            preserve_default=False,
        ),
    ]
